premio = float(input("Digite o valor do prêmio: "))
desconto = float(premio * 0.07)
primeiro = float(desconto * 0.46)
segundo = float(desconto * 0.32)
terceiro = float(desconto * 0.15)
print("O valor que o primeiro ganhou: ", primeiro)
print("O valor que o segundo ganhou: ", segundo)
print("O valor que o terceiro ganhou: ", terceiro)
print("O desconto foi de: ", desconto)